#include <types.h>
#include <utils.h>
#include <broadcom.h>

#define UART_BASE (PERIPHERAL_BASE + 0x201000)

#define UART_DATA ((MMIO_32)(PERIPHERAL_BASE + 0x00))
#define UART_FLAG ((MMIO_32)(PERIPHERAL_BASE + 0x18))
#define UART_IBAUD_DIVISOR ((MMIO_32)(PERIPHERAL_BASE + 0x24))
#define UART_FBAUD_DIVISOR ((MMIO_32)(PERIPHERAL_BASE + 0x28))
#define UART_LINE_CONTROL ((MMIO_32)(PERIPHERAL_BASE + 0x2C))
#define UART_CONTROL ((MMIO_32)(PERIPHERAL_BASE + 0x30))
